language: cpp

compiler: gcc

env:
- QT_BASE=53

before_install:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- |
  if [ "$CXX" = "clang" ]; then
    sudo sh -c "echo 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.6-binaries main' >> /etc/apt/sources.list"
    sudo sh -c "echo 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise main' >> /etc/apt/sources.list"
    wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
  fi
- if [ "$QT_BASE" = "53" ]; then sudo add-apt-repository ppa:beineri/opt-qt532 -y; fi
- sudo apt-get update -qq

install:
- sudo apt-get install -qq g++-4.9 gcc-4.9
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
- |
  if [ "$CXX" = "clang" ]; then
    sudo apt-get install -qq llvm-3.6
    export CXX="clang++" CC="clang"
  fi
- $CXX --version
- sudo apt-get install -qq qt${QT_BASE}base qt${QT_BASE}script; source /opt/qt${QT_BASE}/bin/qt${QT_BASE}-env.sh

script:
- qmake -r "QMAKE_CXX=$CXX" "QMAKE_CC=$CC"
- make
