install:
  - sudo apt-get update
  - sudo apt-get install libqt4-dev qt4-qmake
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq gcc-4.8
  - sudo apt-get install -qq g++-4.8
  - export CC="gcc-4.8"
  - export CXX="g++-4.8"
  - export CFLAGS=-std=c++11
  - export CXXFLAGS=-std=c++11

script:
  - qmake -project
  - qmake CDansLair.pro
  - make
